### ISSUE TITLE
跑baseline时Dataloader出错

### ISSUE THREAD

**Issue by semikonductor** [qcf-568/Det_Baseline#2]
大佬你好，我在跑赛方提供的baseline的时候遇到错误，无法解决，想请您解答一下。
我使用cv2pk生成了train.pk，总共102w个item。报错信息如下：
```bash
Traceback (most recent call last):
  File "tools/train.py", line 133, in <module>
    main()
  File "tools/train.py", line 129, in main
    runner.train()
  File "/home/challenge/anaconda3/envs/baseLine/lib/python3.8/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/challenge/anaconda3/envs/baseLine/lib/python3.8/site-packages/mmengine/runner/loops.py", line 98, in run
    self.run_epoch()
  File "/home/challenge/anaconda3/envs/baseLine/lib/python3.8/site-packages/mmengine/runner/loops.py", line 114, in run_epoch
    for idx, data_batch in enumerate(self.dataloader):
  File "/home/challenge/anaconda3/envs/baseLine/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/home/challenge/anaconda3/envs/baseLine/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/challenge/anaconda3/envs/baseLine/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/challenge/anaconda3/envs/baseLine/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/challenge/anaconda3/envs/baseLine/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/challenge/anaconda3/envs/baseLine/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/challenge/anaconda3/envs/baseLine/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/challenge/anaconda3/envs/baseLine/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 410, in __getitem__
    data = self.prepare_data(idx)
  File "/home/challenge/anaconda3/envs/baseLine/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 793, in prepare_data
    return self.pipeline(data_info)
  File "/home/challenge/anaconda3/envs/baseLine/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 60, in __call__
    data = t(data)
  File "/home/challenge/anaconda3/envs/baseLine/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/home/challenge/dataset/mmdet_bisai/mmdet/structures/bbox/box_type.py", line 267, in wrapper
    return func(self, results)
  File "/home/challenge/dataset/mmdet_bisai/mmdet/datasets/transforms/transforms.py", line 1648, in transform
    results = self.aug(**results)
  File "/home/challenge/anaconda3/envs/baseLine/lib/python3.8/site-packages/albumentations/core/composition.py", line 346, in __call__
    self.preprocess(data)
  File "/home/challenge/anaconda3/envs/baseLine/lib/python3.8/site-packages/albumentations/core/composition.py", line 373, in preprocess
    raise ValueError(msg)
ValueError: Key img_path is not in available keys.
```

**Comment by semikonductor** [comment]
按照官方库的requirement安装一遍就好了

**Comment by qcf-568** [comment]
可能albu版本错误

**Comment by semikonductor** [comment]
albu版本错误，按照requirement.txt检查一遍就好了
